erickt/rust-zmq

src/lib.rs
Even though `zmq_proxy` is guaranteed to always return with an error, I found it reasonable to still translate that error to clear C `errno`. Maybe not a good idea?
=> Add zmq::proxy and zmq::proxy_with_capture functions

src/lib.rs
I'm pretty sure that we should be looping on `EINTR`, e.g. when a signal interrupts the call, not `EFAULT`, which [represents](http://api.zeromq.org/4-1:zmq-ctx-destroy) a faulty context, so trying it again probably won't suddenly make it a valid context. The comment on line 278 seems to reinforce this idea.
/// Try to destroy the context. This is different than the destructor; the
/// destructor will loop when zmq_ctx_destroy returns EINTR
=> destroy loop on EINTR, not EFAULT

.gitignore, Cargo.toml, examples/zguide/tasksink/main.rs, examples/zguide/taskvent/main.rs, examples/zguide/taskwork/main.rs
I'm not sure what the best is to get the bytes out of a Message object (in taskwork crate). If there's something better or more efficient than msg.as_str().unwrap().bytes() I'd be happy to fix the example.
=> add parallel task examples to zguide

zmq-sys/Cargo.toml, zmq-sys/build.rs
This PR allows for setting the prefix of the libzmq directory at compile time. If the prefix is not provided then we fallback to pkg-config to identify the best possible place
=> add build script which allows setting libzmq prefix

src/lib.rs
Specifically: socket.recv_multipart(), socket.send_multipart(), and socket.poll().
The logic for these functions is copied from the python zeromq bindings:
send_multipart: https://github.com/zeromq/pyzmq/blob/master/zmq/sugar/socket.py#L326
recv_multipart: https://github.com/zeromq/pyzmq/blob/master/zmq/sugar/socket.py#L370
poll: https://github.com/zeromq/pyzmq/blob/master/zmq/sugar/socket.py#L513
=> Add some convenience methods

.travis.yml, Cargo.toml, build.rs, examples/zguide/helloworld_server/main.rs, examples/zguide/msreader/main.rs, examples/zguide/taskwork/main.rs, src/lib.rs, zmq-sys/Cargo.toml, zmq-sys/src/ffi.rs, zmq-sys/src/lib.rs
This is a bit of a big change, but it brings the binding up-to-date with ZeroMQ 4.1, including auth mechanisms (Plain, Curve, GSSAPI) etc. If it's in the C lib, you should now be able to do it with Rust.
Note: Some fns have been removed or their signatures changed to bring the library into compliance with ZMQ4.1.
Feedback most welcome! I am still a Rust rookie.
=> Update binding to ZMQ 4.1

src/lib.rs
Need these methods (to/from/borrow_raw) for passing Sockets to CZMQ structs (ZPoller etc.).
I've also changed the semantics of closing a socket - If we're closing the socket, it makes sense to destroy it, and if we're going to destroy it, we may as well just handle it implicitly. What do you think?
=> Raw socket interface

tests/test.rs
This change adds missing integration of compiletest-rs into the test
suite, so compiletests are run by "cargo test" if the compiletest_rs
feature is selected. Also, pull compiletest-rs directly from github, as
the last-published version didn't compile with the rustc from current
master.
=> Activate compiletest_rs feature

src/lib.rs, src/sockopt.rs
- Move low-level sockopt setting/getting code into its own module
`sockopt`. Introduce traits `Getter` and `Setter` to provide generic
interface for the most common option types.
- Using those traits, construct a macro `sockopts!` that allows
declaring many options at once, reducing an accessor pair to a single
line in most cases. It also allows grouping feature-dependent
accessors.
Note that this change eliminates the string allocation using
`ffi:String` in `set_zap_domain()`. This should be unecessary, since all
zmq socket options requiring C-like strings should be treat the
NUL-terminator as optional, as they also are provided the length (see
https://github.com/zeromq/libzmq/issues/2169).
No public API changes should be introduced, but this can be seen as a
preparation for fixing #100, …
=> Reduce sockopt boilerplate using macros

.travis.yml
It seems SSL on the travis build machines is partially broken, maybe
lacking the letsencrypt root certificate. Work around that by just
cloning the repo from github, which works. Explicitly specifying the LE
root certificate, did not, neither did trying plain HTTP, as that
redirects to HTTPS.
Additionally, use the currently latest libsodium (1.0.11).
=> Try to work around travis failure

README.md, examples/zguide/helloworld_client/main.rs, examples/zguide/helloworld_server/main.rs, examples/zguide/msreader/main.rs, examples/zguide/tasksink/main.rs, examples/zguide/taskvent/main.rs, examples/zguide/taskwork/main.rs, examples/zguide/weather_client/main.rs, examples/zguide/weather_server/main.rs, src/lib.rs, tests/compile-fail/no-leaking-poll-items.rs, tests/shared-context.rs, tests/test.rs
Based on alexcamp's work, specifically commits 25fb5820..dbadcb81, this
API change allows sharing a `Context` between threads, while still being
able to create sockets from them.
This is a thing possible in C (obviously), but was forbidden by the Rust
API, due to `Context::socket` taking a mutable self reference. The zmq
context is thread-safe, as noted in zmq(7):
A ØMQ context is thread safe and may be shared among as many
application threads as necessary, without any additional locking
required on the part of the caller.
As dropping a context with live sockets is a defined action, as well,
according to zmq_ctx_destroy(3), it should be safe to enable the
creation of sockets via aliases to the context in different threads.
This commit should fix issue #64.
=> Don't require a mutable borrow to create sockets

src/lib.rs, tests/shared-context.rs
This resolves #110, and puts it to test by extending the shared-context
test code to also create a TCP endpoint using an ephemeral port.
=> Add `ZMQ_LAST_ENDPOINT` getter

src/lib.rs
These are logically independent, but touch the same code, so I thought it's best to put them into one PR.
Commits should be reviewed independently.
As for the last change, I thought it was best not to put the `unsafe {}` into the macro, to avoid hiding unsafe code locations.
=> Some bug fixes and idiomatic changes

examples/msgsend/main.rs, examples/zguide/fileio3/main.rs, examples/zguide/helloworld_client/main.rs, examples/zguide/helloworld_server/main.rs, examples/zguide/msreader/main.rs, examples/zguide/rtdealer/main.rs, examples/zguide/tasksink/main.rs, examples/zguide/taskvent/main.rs, examples/zguide/taskwork/main.rs, examples/zguide/weather_client/main.rs, examples/zguide/weather_server/main.rs, src/lib.rs, tests/compile-fail/socket-thread-unsafe.rs, tests/shared-context.rs, tests/test.rs
Note that this is really a single commit being proposed, which depends on PR #96. Github does not handle outstanding PRs that depend on each other well, unfortunatly.
=> 	Make most socket methods operate on immutable self

Cargo.toml, build.rs, src/lib.rs, zmq-sys/Cargo.toml, zmq-sys/build.rs, zmq-sys/src/errno.rs, zmq-sys/src/lib.rs, zmq-sys/src/win_errno.rs
There is also a fix for an off-by-one memory error. All tests passing on rustc 1.12.0 i686-pc-windows-msvc and rustc 1.12.0 x86_64-unknown-linux-gnu.
=> Support for Windows (Updated)

.appveyor.yml, .appveyor/appveyor.bat, Cargo.toml, build.rs, src/lib.rs, tests/shared-context.rs, tests/test.rs, zmq-sys/Cargo.toml, zmq-sys/build.rs, zmq-sys/src/errno.rs, zmq-sys/src/lib.rs, zmq-sys/src/win_errno.rs
This fixes appveyor integration with zeromq. It also merges in @tcosprojects's #94 windows fixes, which gets most, but not all, tests to pass on appveyor. The current output can be seen [here](https://ci.appveyor.com/project/erickt/rust-zmq/build/1.0.147). Specifically the tests that fail are:
```
failures:
test_exchanging_bytes
test_exchanging_messages
test_exchanging_multipart
test_exchanging_strings
test_polling
```
I'm fine landing this in this current state, we can fix these test failures in a future patch.
=> Fix appveyor and get most windows tests to pass

Cargo.toml, zmq-sys/Cargo.toml
The master branch is now headed towards a new, API-incompatible
release, hence the bump to 0.9.
=> Bump version to 0.9.0

NEWS.md, src/lib.rs
This does not need to be exposed directly, and we should not even need
to derive the Rust value from the raw one ourselves.
=> Remove `Constants` from API

NEWS.md, examples/msgsend/main.rs, examples/zguide/fileio3/main.rs, examples/zguide/helloworld_client/main.rs, examples/zguide/helloworld_server/main.rs, examples/zguide/lvcache/main.rs, examples/zguide/msreader/main.rs, examples/zguide/pathopub/main.rs, examples/zguide/rtdealer/main.rs, examples/zguide/taskvent/main.rs, examples/zguide/taskwork/main.rs, examples/zguide/weather_server/main.rs, src/lib.rs, tests/compile-fail/socket-thread-unsafe.rs, tests/shared-context.rs, tests/test.rs
This fixes #118, and allows for implementation of the `From<&[u8]>`
and `From<Vec<u8>` for `Message`.
=> 	Make message allocation infallible, and reap some benefits

src/lib.rs, src/sockopt.rs, tests/test.rs
This has been re-applied based on commit 1804c88, now that the 0.8
release is out of the way.
The change to make `get_fd()` return `RawFd`, which was part of that
commit, has not been included, as this would fail compilation on
Windows.
=> Make curve key and identity accessors operate on binary data

tests/test.rs
On windows, connect() call fails when using the
return of get_last_endpoint() after a wild-card
bind, "tcp://0.0.0.0:<PORT>".
Instead, we must use the form
"tcp://127.0.0.1:<PORT>". This behavior is seen
in the libzmq library[1] itself.
[1]: https://github.com/zeromq/libzmq/blob/905286261969d4e4b1b956f2befacb8c1eae5e35/tests/test_unbind_wildcard.cpp#L45-L49
=> Fix connect()-related Appveyor/win test failures

tests/test.rs
connecting() to an endpoint bound with wildcard
("*:*") is not necessarily defined behavior, and
does not work on windows. Use "127.0.0.1:*" instead
in tests.
=> bind "127.0.0.1:*" instead of "*:*"

src/lib.rs, tests/test.rs
Fixes windows tests failing due to trying to ``connect()`` to and endpoint from a wildcard (``"*:*"``) bind.
Updates ``PollItem`` struct field ``fd`` to ``RawSocket`` type from ``zmq-sys`` crate, to fix ``test_polling``.
=> Fixes for failing windows test, based on release/v0.8 branch

tests/shared-context.rs
This now also smoke-tests polling, and is has been refactored a bit.
=> Extend shared-context test

src/lib.rs, tests/test.rs
=> Allow converting `Error` into `std::io::Error`

src/lib.rs
Change the type of `events` and `revents` from `i16` to `c_short`,
which it what is used in the C headers.
=> Adjust poll event types

Cargo.toml, src/lib.rs, src/sockopt.rs, tests/compile-fail/no-leaking-poll-items.rs, tests/connection/unix.rs
This improves type safety, and allows code to written in a more
readable style, at least for those not well-versed in C bitmaskery.
On the flip side, this is another incompatible API change.
=> Introduce bitflags type for polling events

zmq-sys/Cargo.toml, zmq-sys/build.rs
This makes it easier for distribution packaging tools to generate
appropriate package dependencies.
=> Use metadeps to specify pkg-config dependencies declaratively

src/lib.rs
Fixes #141. The added text does not mention Windows explicitly, but I
don't think it's a good practice to try to connect to "0.0.0.0" on any
platform.
=> Add documentation for `get_last_endpoint`

src/lib.rs
* Add accessor for probe router
* Add accessor for router mandatory
=> Add missing sockopt accessors

tests/curve.rs, tests/test.rs
This is a adapted version of the code posted in #164, taking
`tests/test_security_curve.cpp` from the libzmq test suite as a
template.
=> Add curve smoke test

src/lib.rs, tests/test.rs
It is part of the C API and missing here.
The merge request is against the release/0.8 as adding a method should be API compatible change. Sorry I didn't open an issue for it upfront, I read the Contribution notes only after doing it, but I guess there's no other way the method could look like anyway and there's very little code written so it wouldn't matter if it would get thrown away.
As for motivation, I'd like to be able to shut down a worker gracefully, without losing messages in the input queue. If I disconnect first, I can process all messages in the queue and new ones won't arrive.
=> Add Socket::disconnect method

zmq-sys/build.rs
This is a slightly cleaned up version of PR #166.
=> Make LIBZMQ_PREFIX construct valid Windows paths

src/lib.rs, tests/error.rs
Fixes #174. Drop for RawContext has a while EINTR loop handling
system interupts, however Error::from_raw cannot return this
Error. Adding it to the match allows this errno to be handled.
=> Fix EINTR errno -> Error (release/v0.8)

src/lib.rs, tests/poll.rs, tests/poll/unix.rs
This rectifies missing API coverage: there was previously no way to
construct a `PollItem` from an arbitrary file descriptor with a
non-zero event field.
Fixes #193.
=> Add `PollItem::set_events`

src/lib.rs, tests/poll/unix.rs
As the set of events to poll for needs to be set in every case, let
the caller specify it up front, instead of having to invoke
`PollItem::set_events` after creating the poll item.
=> Let `PollItem::from_fd` take the events to poll for

Cargo.toml, examples/zguide/monitor/main.rs, src/lib.rs
Add support for configuring a socket for tracking socket events.  This includes creating a wrapper function on Socket for the `zmq_socket_monitor` call, a `SocketEvents` enum and a monitor example.
Note, the example, which is based on the [libzmq C example](http://api.zeromq.org/4-1:zmq-socket-monitor), hangs after receives two of the events on client monitor socket. Any feed back for that error would be appreciated.
=> Add support for ZMQ Monitor Sockets

src/lib.rs
I accidentally found myself in the multiple NICs situation described in:
https://zeromq.jira.com/browse/LIBZMQ-556
so I thought adding the `set_router_handover` method would be an easy PR to get merged? Right now I am using zmq-sys as a workaround, but having to write my own `unsafe{}` code isn't ideal.
=> add ZMQ_ROUTER_HANDOVER methods

zmq-sys/src/errno.rs, zmq-sys/src/lib.rs, zmq-sys/src/unix.rs
In `zmq-sys`, the use of the `#[path]` attribute to make things more cross-platform causes an ICE when running `cargo doc` on nightly.
cc: rust-lang/rust#47391
=> Replaced #[path] with some #[cfg] attributes to avoid an ICE

build.rs, tests/has.rs
Before this commit, `zmq::has` will always return `None` because the
compiler flag ZMQ_HAS_ZMQ_HAS wasn't set at all when feature `zmq_has`
was enabled, and was incorrectly set (typo "rust-cfg" instead of
"rustc-cfg") when the `zmq_has` feature was not enabled, but a
new-enough version of libzmq was detected.
This commit makes the necessary adjustments to the build script, and
adds a test to check that zmq::has is actually being called (i.e. it
returns Some(_)).
=> Fix `zmq::has` feature detection

.travis.yml, Cargo.toml, examples/zguide/pathopub/main.rs, examples/zguide/pathosub/main.rs, src/lib.rs, tests/compile-tests.rs, tests/z85.rs
- The `compiletest_rs` crate now works on stable Rust, so remove the
`unstable-testing` feature, and run always run the compile
tests. The feature removal is, strictly speaking, a breaking change,
but can be arguably be justified to be non-breaking for normal
users, as it is not a feature to be enabled by dependant crates. In
the same vein, the `unstable` feature has been removed, which seemed
to be an unused leftover.
- The `bitflags` crate had changes in the syntax and semantics of the
`bitflags` macro, requiring adding top-level constants for `POLLIN`,
`POLLOUT` and `POLLERR` to maintain backward compatibility.
- The `rand` crate had some breaking changes between 0.5 and 0.6,
which required some small changes in the test suite.
=> Update crate dependencies

.travis.yml, examples/zguide/lbbroker/main.rs, examples/zguide/monitor/main.rs, examples/zguide/pathopub/main.rs
- Ensure compatibility back to rustc 1.32
- Run `cargo check` upfront, before running the full matrix
- Do a staged build (check, test, lint)
- Include running a rustfmt check in the lint phase (fixes #263)
=> CI: Update travis build

build.rs, tests/compile-tests.rs
The following was failing:
```
cargo clean
cargo test --release
```
=> Fix `compile_test` for release mode

.appveyor.yml, .appveyor/appveyor.bat, .travis.yml, Cargo.toml, NEWS.md, zmq-sys/Cargo.toml, zmq-sys/build/main.rs, zmq-sys/build/pkg_config.rs, zmq-sys/build/vendored.rs
This is the reopening of #262 since github does not allow the reopening of PRs after you force push.
The vendored crate now compiles statically, adding dynamic compilation down the line would be trivial.
=> Added vendored build support

src/message.rs, tests/curve.rs, tests/message.rs, tests/test.rs
The `with_capacity_unallocated`, `with_capacity` and `from_slice`
methods are deprecated, the first one without a planned alternative.
=> Deprecate several `Message` methods

zmq-sys/Cargo.toml
Fixes #283.
I know that `0.1.6` is equivalent to `^0.1.6`, so this is not strictly needed, but we are never too safe.
=> Bumped zeromq-src dependency to 0.1.7

examples/zguide/fileio3/main.rs, tests/common/mod.rs
These were identified by current beta clippy (1.38):
- `ONCE_INIT` is now deprecated.
- Superfluous `'static` lifetime on static variable.
=> Fix clippy warnings

Cargo.toml, src/lib.rs
When using rust-zmq in an application, I noticed some log entries when dropping sockets. IMO this doesn't provide any useful information, so I removed it here. If you don't agree with this, just close the PR :)
Logging isn't used anywhere else in the library code, so this change also allows removing the dependency on the `log` crate from the non-dev section.
=> Remove log code from library

src/lib.rs, tests/poll/unix.rs, tests/test.rs
Adds is_socket and is_fd to PollItem to allow checking which socket a
PollItem has been created from.
Enables some use cases related to #68.
=> PollItem: Support checking associated socket

.gitignore, .travis.yml, README.md, examples/zguide/mtrelay/main.rs, msrv-test/Cargo.toml, msrv-test/src/main.rs, src/lib.rs, src/message.rs, tests/compile-tests.rs
There's some new tricks clippy learned, and more importantly building is broken on 1.32 due to some `dev-dependencies` requiring new language features. Since `dev-dependencies` should not affect downstream compilation, we should probably not do a full build on 1.32 anymore, but instead just ensure that the code still compiles.
=> Attempt to fix the CI build

src/lib.rs
The `description` method has been soft-deprecated for some time now,
and current nightly (1.41) warns upon its use:
warning: use of deprecated item 'std::error::Error::description': use the Display impl or to_string()
Since our `description` implementation made use of the underlying
error's `description` method, we triggered that warning. Let's fix
that by just getting rid of the implementation containing the
offending code.
=> Remove `std::error::Error` description method implementations

src/lib.rs, tests/test.rs
The new method provides an alternative to the `description` method on
`std::error::Error`, which is soft-deprecated, and current beta clippy
warns about its use.
=> Provide inherent method to get error message string

Cargo.toml, tests/compile-fail/no-leaking-poll-items.rs, tests/compile-fail/no-leaking-poll-items.stderr, tests/compile-fail/socket-thread-unsafe.rs, tests/compile-fail/socket-thread-unsafe.stderr, tests/compile-tests.rs
trybuild is a bit more of a robust test suite, which uses cargo instead of rustc to drive the build.
=> Switch from compiletest_rs to trybuild

tests/monitor.rs
Closing the client and server sockets at the same time allows each side
to race to disconnect the peer. Close the server socket after it is
"disconnected".
=> Fix flaky `test_monitor_events` test

tests/message.rs, zmq-sys/src/errno.rs
Fix `error: redundant clone`
Fix `error: unnecessary parentheses around assigned value`
=> Fix errors with clippy 1.44.1

src/lib.rs
=> implement AsRawFd

src/lib.rs, tests/context.rs
Fixes #206
Specific getters and setters are used following the precedence from `Socket`.
=> Add `Context` getters and setters for `ZMQ_IO_THREADS`

zmq-sys/Cargo.toml, zmq-sys/build/vendored.rs
* Update to zeromq-src with bumps libzmq version to 4.3.4 and
enables building without cmake.
* Link against libsodium for encryption support for security
and performance reasons.
Note that im unsure whether libsodium should be linked by default since I'm assuming not all users use CURVE.
=> Move to zeromq-src 0.2

zmq-sys/Cargo.toml, zmq-sys/build/pkg_config.rs
`metadeps` hasn't seen an update and crate release for 4-5 years, with `system-deps` being a fork and actively maintained successor to it.
=> zmq-sys: Replace `metadeps` with `system-deps` successor

src/message.rs
Add `Message::from_raw` to create a `Message` from an initialized
`zmq_msg_t`. This is useful for wrapping messages created with
`zmq_msg_init_data`.
=> Message: Add pub unsafe fn `from_raw`

src/lib.rs
=> Fixed memory leak in zmq::z85_decode

.github/workflows/ci.yaml, src/lib.rs, src/message.rs, src/sockopt.rs, tests/compile-fail/no-leaking-poll-items.stderr, tests/compile-fail/socket-thread-unsafe.stderr, tests/message_from_boxed_slice.rs, tests/monitor.rs, tests/test.rs, tests/z85.rs
- **Recommit Rust 1.83 compile-fail output**
- **Automatically fix new clippy lints on Rust 1.83**
- **Drop stale `compiletest` code**
- **Manually fix remaining clippy lints**
=> Fix clippy lints since Rust 1.83

zmq-sys/Cargo.toml
This release includes a fix for cross-compiling, and bumps the ZeroMQ source to v4.3.5.
=> Upgrade `zeromq-src` to `0.3`

src/message.rs
Rationale: this complements the `Deref` and `DerefMut` impls, and allows Message to be used directly in I/O constructs like `std::io::Cursor`, which makes it a lot easier to implement reads.
=> Message: impl `AsRef<[u8]>`, `AsMut<[u8]>`
